name = "router"
main = "./.vidro/server-entry.ts"
compatibility_date = "2026-04-17"

[assets]
directory = "./.vidro/build/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

run_worker_first = true
