import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { readdir } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import type { Plugin } from "vite-plus";

// routes/ ディレクトリを walk して `RouteMap` interface を module augmentation
// する `.d.ts` を生成する vite plugin。`routes/users/[id]/index.tsx` のような
// ファイル配置から `"/users/:id": { params: { id: string } }` を起こし、
// `LoaderArgs<"/users/:id">` / `PageProps<typeof loader>` のどちらも Routes
// 辞書経由で type-safe に使えるようにする (ADR 0011)。
// 生成物は vite root 直下の `.vidro/routes.d.ts` に出す (ADR 0013)。
// tsconfig base は plugin package に同梱されている (`@vidro/plugin/tsconfig.base.json`)
// ので、user tsconfig が extends するだけで Vidro が必要とする compilerOptions
// が揃う。

export type RouteTypesOptions = {
  /** routes ディレクトリ (vite root 相対)。default: "src/routes" */
  routesDir?: string;
  /** 出力先 .d.ts (vite root 相対)。default: ".vidro/routes.d.ts" */
  outFile?: string;
};

/** @vidro/plugin の routeTypes plugin 本体。 */
export function routeTypes(options: RouteTypesOptions = {}): Plugin {
  const routesDirOpt = options.routesDir ?? "src/routes";
  // 生成物は vite root 直下の `.vidro/` に集約 (SvelteKit `.svelte-kit/` /
  // Astro `.astro/` 式)。`.gitignore` に `.vidro/` を入れて artifact 扱いにする。
  const outFileOpt = options.outFile ?? ".vidro/routes.d.ts";

  let routesDirAbs = "";
  let outFileAbs = "";

  return {
    name: "vidro-route-types",
    async configResolved(config) {
      routesDirAbs = resolve(config.root, routesDirOpt);
      outFileAbs = resolve(config.root, outFileOpt);
      await generate(routesDirAbs, outFileAbs);
    },
    async buildStart() {
      // watch 外から呼ばれる CLI (vp build 等) でも確実に生成されるよう二重化。
      await generate(routesDirAbs, outFileAbs);
    },
    configureServer(server) {
      // routesDir 配下の index.tsx / layout.tsx の add/unlink/rename で再生成。
      // 既存ファイルの編集は RouteMap の形を変えないので listen しない (再生成
      // コストを抑える)。
      const handler = async (file: string) => {
        if (!file.startsWith(routesDirAbs)) return;
        if (!isRouteShapeFile(file)) return;
        await generate(routesDirAbs, outFileAbs);
      };
      server.watcher.on("add", handler);
      server.watcher.on("unlink", handler);
      // dir 単位の削除 (rename 等) は file 粒度の event が来ないことがあるので
      // 無条件で regenerate する。routes 数が多くない toy runtime 段階では十分。
      server.watcher.on("unlinkDir", () => {
        void generate(routesDirAbs, outFileAbs);
      });
    },
  };
}

// --- internal helpers ---

function isRouteShapeFile(filePath: string): boolean {
  return /[\\/](index|layout)\.tsx$/.test(filePath);
}

// routes/ を再帰的に walk し、index.tsx / layout.tsx が存在する dir の URL
// pattern をすべて collect する。dir 単位で dedupe するので、同 dir に
// index.tsx + layout.tsx が両方あっても 1 entry になる。
async function collectRoutePaths(routesDirAbs: string): Promise<string[]> {
  if (!existsSync(routesDirAbs)) return [];
  const paths = new Set<string>();
  await walk(routesDirAbs, routesDirAbs, paths);
  return Array.from(paths).sort();
}

async function walk(dir: string, routesDirAbs: string, out: Set<string>): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full, routesDirAbs, out);
      continue;
    }
    if (entry.name !== "index.tsx" && entry.name !== "layout.tsx") continue;
    const rel = relative(routesDirAbs, dir);
    out.add(dirToRoutePath(rel));
  }
}

// "users/[id]" → "/users/:id"、"" (routes 直下) → "/"
function dirToRoutePath(rel: string): string {
  if (rel === "") return "/";
  const parts = rel.split(/[\\/]/).map((p) => p.replace(/^\[([^\]]+)\]$/, ":$1"));
  return "/" + parts.join("/");
}

// "/users/:id" から ["id"]、"/" から []
function extractParams(path: string): string[] {
  const names: string[] = [];
  const re = /:([^/]+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(path)) !== null) names.push(m[1]!);
  return names;
}

function renderDts(paths: string[]): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @vidro/plugin routeTypes() — DO NOT EDIT");
  // side effect import で @vidro/router の module resolution を確実に発火させ、
  // その上で interface augmentation を重ねる。`export {}` 相当のファイル種別も
  // この import が担うので別途入れる必要は無い。
  lines.push('import "@vidro/router";');
  lines.push("");
  lines.push('declare module "@vidro/router" {');
  lines.push("  interface RouteMap {");
  for (const p of paths) {
    const params = extractParams(p);
    const paramsType =
      params.length === 0
        ? "Record<string, never>"
        : `{ ${params.map((n) => `${n}: string`).join("; ")} }`;
    lines.push(`    "${p}": { params: ${paramsType} };`);
  }
  lines.push("  }");
  lines.push("}");
  return lines.join("\n") + "\n";
}

async function generate(routesDirAbs: string, outFileAbs: string): Promise<void> {
  const paths = await collectRoutePaths(routesDirAbs);
  const content = renderDts(paths);
  mkdirSync(dirname(outFileAbs), { recursive: true });
  // 同一内容なら書き出さない (vite HMR が無駄に走らないように)
  let existing = "";
  if (existsSync(outFileAbs)) {
    try {
      existing = readFileSync(outFileAbs, "utf8");
    } catch {
      existing = "";
    }
  }
  if (existing !== content) writeFileSync(outFileAbs, content, "utf8");
}
